name: build-test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev \
            libxkbcommon-dev libwayland-dev wayland-protocols extra-cmake-modules \
            libasound2-dev libpulse-dev

      - uses: actions/checkout@v6 

      - run: cmake -S . -B build

      - run: cmake --build build --config Release

      - run: ctest --test-dir build --build-config Release --output-on-failure


